package Modelo;
// Generated Mar 22, 2016 2:35:56 PM by Hibernate Tools 4.3.1



/**
 * Contrasenha generated by hbm2java
 */
public class Contrasenha  implements java.io.Serializable {


     private int idcontrasenha;
     private Usuario usuario;
     private String scontrasenha;

    public Contrasenha() {
    }

	
    public Contrasenha(int idcontrasenha, String scontrasenha) {
        this.idcontrasenha = idcontrasenha;
        this.scontrasenha = scontrasenha;
    }
    public Contrasenha(int idcontrasenha, Usuario usuario, String scontrasenha) {
       this.idcontrasenha = idcontrasenha;
       this.usuario = usuario;
       this.scontrasenha = scontrasenha;
    }
   
    public int getIdcontrasenha() {
        return this.idcontrasenha;
    }
    
    public void setIdcontrasenha(int idcontrasenha) {
        this.idcontrasenha = idcontrasenha;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getScontrasenha() {
        return this.scontrasenha;
    }
    
    public void setScontrasenha(String scontrasenha) {
        this.scontrasenha = scontrasenha;
    }

}