package Modelo;
// Generated Mar 22, 2016 2:35:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String scorreo;
     private String snombreusuario;
     private Set contrasenhas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idusuario, String scorreo, String snombreusuario) {
        this.idusuario = idusuario;
        this.scorreo = scorreo;
        this.snombreusuario = snombreusuario;
    }
    public Usuario(int idusuario, String scorreo, String snombreusuario, Set contrasenhas) {
       this.idusuario = idusuario;
       this.scorreo = scorreo;
       this.snombreusuario = snombreusuario;
       this.contrasenhas = contrasenhas;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getScorreo() {
        return this.scorreo;
    }
    
    public void setScorreo(String scorreo) {
        this.scorreo = scorreo;
    }
    public String getSnombreusuario() {
        return this.snombreusuario;
    }
    
    public void setSnombreusuario(String snombreusuario) {
        this.snombreusuario = snombreusuario;
    }
    public Set getContrasenhas() {
        return this.contrasenhas;
    }
    
    public void setContrasenhas(Set contrasenhas) {
        this.contrasenhas = contrasenhas;
    }




}


